### ISSUE TITLE
When files moved from one directory to another the original files are not deleted on the peer

### ISSUE THREAD

**Issue by erangell** [beakerbrowser/hashbase#105]
To replicate:
Create a DAT website.  Add a subdirectory and add some files to it.  Publish it to hashbase.
Create a sub-subdirectory under the subdirectory you created.
Move the files from the subdirectory to the sub-subdirectory.  Publish your changes.
On another machine, go to the DAT URL.
Both the subdirectory and the sub-subdirectory contain the files.
If this is a problem with the DAT protocol, please open an issue with the appropriate project.

**Comment by pfrazee** [comment]
Thanks for reporting. Let me get some sense of how it's happening...

> Create a DAT website. Add a subdirectory and add some files to it. Publish it to hashbase.
> Create a sub-subdirectory under the subdirectory you created.
> Move the files from the subdirectory to the sub-subdirectory. Publish your changes.

How are you doing the publishing here? With the dat cli or with Beaker? Which version?

**Comment by erangell** [comment]
The publishing is done with Beaker.  I am running Beaker v0.8.0-prerelease.9 
Whoever works on this may want to look into how Git handles detection of files that moved and implement similar logic.

**Comment by pfrazee** [comment]
Do the files appear to have been moved in beaker when you look at the files listing?

**Comment by erangell** [comment]
It appears that this may only happen when Preview Mode is on.  Today it detected a delete for a new site created with Preview Mode off.  So I have a workaround but other people may experience this if they are looking for a git staging experience.  Attached are screenshots of the versions of the archive at each step when I first found the issue.

![local_site_has_preview_mode_on](https://user-images.githubusercontent.com/5579123/46551750-9d100800-c8a6-11e8-8c9d-b8b3891495fd.png)
![v20_created_transcripts_dir_added_1_file](https://user-images.githubusercontent.com/5579123/46551751-9d100800-c8a6-11e8-9530-b78b90eaacdd.png)
![v19_no_transcripts_dir](https://user-images.githubusercontent.com/5579123/46551752-9d100800-c8a6-11e8-88fb-99f7f4e80821.png)
![v25_files_still_exist_in_transcript_dir](https://user-images.githubusercontent.com/5579123/46551753-9d100800-c8a6-11e8-8c5e-ea5fa2b19d11.png)
![v25_moved_2nd_file_to_unedited_subdir](https://user-images.githubusercontent.com/5579123/46551754-9d100800-c8a6-11e8-94b7-e19a0b16e6e1.png)
![v24_moved_one_file_to_unedited_subdir](https://user-images.githubusercontent.com/5579123/46551756-9d100800-c8a6-11e8-9cfa-05407b3c6451.png)
![v23_created_unedited_dir_under_transcripts](https://user-images.githubusercontent.com/5579123/46551757-9d100800-c8a6-11e8-9621-d6bbd328d5be.png)
![v22_updated_favicon](https://user-images.githubusercontent.com/5579123/46551758-9d100800-c8a6-11e8-8308-02c5d660cdff.png)
![v21_added_another_file_to_transcripts](https://user-images.githubusercontent.com/5579123/46551759-9da89e80-c8a6-11e8-8df3-231806043f93.png)

**Comment by erangell** [comment]
I was able to recreate the issue as follows:
1. Create the directory (DIR) and subdirectory (SUB) in Beaker, with Preview mode on.
2. Make a local copy of the site.
3. Add files to DIR.
4. Publish the site.
5. Completely exit Beaker Browser.
6. Move files from DIR to SUB.
7. Start Beaker Browser.  You will see the file restored in DIR, and they will still exist in SUB.  When you Review Changes, you only see the 2 adds to SUB.  So it looks like the initial sync did not detect the delete of the 2 files from DIR.

**Comment by pfrazee** [comment]
Looks like this is an issue with Beaker and not Hashbase or Dat. What you described is that Beaker is restoring files on startup, which it shouldn't be doing when preview-mode is on.

**Comment by pfrazee** [comment]
Moving to the beaker repo.
