### ISSUE TITLE
Install script for requirements

### ISSUE THREAD

**Issue by kodedninja** [beakerbrowser/hashbase#106]
I'm setting up my personal Hashbase instance (long live decentralization) and the setup isn't just `npm install` as written in the documentation haha.

Spent the last 10 minutes with `npm install` then installing one required program (ex. `python`, `make`, `g++`, `autoconf`).

UPDATE: also bindings for `leveldown` and `sqlite3` were missing after `npm install`.

UPDATE: setting up an instance is pretty hard overall :smile: Sorry for the issue spam, just throwing the notes here to hopefully come back and fix them later.

**Comment by kodedninja** [comment]
Also, I get `RangeError` at connection from a lot of places.

Example:
```
RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (buffer.js:72:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:121:17)
    at Stream.<anonymous> (/root/hashbase/node_modules/handle-thing/lib/handle.js:120:12)
    at Stream.emit (events.js:187:15)
    at endReadableNT (/root/hashbase/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by kodedninja** [comment]
Haha I guessed that from the documentation.

The only issue right now is the `RangeError` from the second comment. Pages are served, but not able to login or register. The 1 GB memory should be enough, right?

**Comment by pfrazee** [comment]
The `RangeError` doesn't sound like a memory access thing but it certainly could be; I haven't run into that. I wouldn't expect 1GB to get eaten with a fresh install but I wouldn't be super surprised either.

**Comment by kodedninja** [comment]
Ah, okay. Do you have any ideas for a fix or on how to check if it's the memory?

If I succeed with the setup, I'll try to make some tutorial on this. We should have more Hashbase instances!

**Comment by pfrazee** [comment]
Agree that we need more Hashbases! And if it were me, I'd just run `htop` and see if the memory usage starts getting close to full

**Comment by kodedninja** [comment]
Checked memory usage. It's far from maximum, but same error. :cry:

**Comment by pfrazee** [comment]
Huh. I don't know what could be causing this.

**Comment by kodedninja** [comment]
Allright, found something. If I disable `letsencrypt`, it works. Will try to play with that.

**Comment by kodedninja** [comment]
Updated `greenlock-express` and now it works. Will PR with my notes!

**Comment by pfrazee** [comment]
Okay good deal
