### ISSUE TITLE
Broken links on https://hashbase.io/about

### ISSUE THREAD

**Issue by tsmall** [beakerbrowser/hashbase#110]
Hello! Browsing the Hashbase website I found that there are two broken links on the About page. In the first two paragraphs the words "Dat protocol" and "Dat" both link to https://github.com/datprotocol/dat. But that's a 404 now.

(P.S. -- I don't know if this is the right place to put this. Apologies if it's not. I couldn't find a repo for the Hashbase website or any other means of contacting you. So I thought this was the best option.)

**Comment by pfrazee** [comment]
@tsmall Thanks for the heads up! This is the correct spot. Fixing now.
