### ISSUE TITLE
Cannot upgrade on hashbase.io

### ISSUE THREAD

**Issue by foggy1** [beakerbrowser/hashbase#114]
This may be a problem with hashbase.io specifically, but if I try to upgrade to pro, entering any valid card yields a `400: spawn ENOMEM`.

**Comment by pfrazee** [comment]
Hey thanks for filing. Hashbase's architecture has basically hit its scaling limit and I'm having trouble keeping the dang thing online. The instance is literally running out of memory on us.

We're replacing it with a v2 architecture in a new service called Beaker.Cloud. If you can wait til mid-summer for that, I'd suggest it! In the meantime I'd be happy to just bump your disk quota on hashbase for free, just let me know how much space you need and what your account name is.

**Comment by foggy1** [comment]
Appreciate the update! I launched my own instance immediately after this, since it's just me I won't have to worry about scaling stuff. Looking forward to the new architecture.
