### ISSUE TITLE
502 for a few minutes now

### ISSUE THREAD

**Issue by millette** [beakerbrowser/hashbase#122]
Hello @pfrazee 

Just noticed 502 (and now, 504) on hashbase.io and hosted sites for the last few minutes. Was working 30 minutes ago.

No more twitter for me, hence this issue...

P.S.: mastodon?

**Comment by pfrazee** [comment]
Yeah sorry, it crashes every so often

**Comment by millette** [comment]
Thanks for the quick fix. I don't use it often... as you noticed, I fell behind a little tiny bit :-)

**Comment by pfrazee** [comment]
Haha alllllll good. We're gonna replace hashbase with something new for
hyper (but leave it running for legacy)

**Comment by millette** [comment]
For instance <https://github.com/hypercore-protocol/hyperdrive-daemon/issues/68> *wink wink*
