### ISSUE TITLE
Upload progress bar stalls even after process completes

### ISSUE THREAD

**Issue by emanuelfeld** [beakerbrowser/hashbase#54]
The progress bar has been stuck at 98%, though the site is accessible via dat://trump-but-only-emanuelfeld.hashbase.io/ and I've been able to push new changes, which are reflected on the site hashbase is seeding.

![image](https://user-images.githubusercontent.com/4269640/31733342-5b684910-b409-11e7-922b-e498533856a6.png)

**Comment by pfrazee** [comment]
I noticed that. Thanks for reporting.
