### ISSUE TITLE
new-archive->Browse yields "[object Object]"

### ISSUE THREAD

**Issue by suttonwilliamd** [beakerbrowser/hashbase#77]
Steps to reproduce:

1. Log in.
2. Click "Upload archive".
3. Click "Browse".
4. Select an archive to upload from your library.
5. Finally, click "Select".

Intended behaviour: 
dat url of selected archive goes into the URL field
(maybe) name of archive (on disk, not display name*) is placed in Name field

* display names (or whatever they're really called) can include spaces and special characters

Instead what happens: 
URL field is populated with "[object Object]"

**Comment by pfrazee** [comment]
Fixed!
