### ISSUE TITLE
upload content failed

### ISSUE THREAD

**Issue by Evanlai8** [beakerbrowser/hashbase#82]
I try to deploy hashbase in my Local computer and  Service 
Everything is alright in Local instance, Uploading successed both metadata and content.
In Service, metadata was uploaded succeesfully but the content was failed, the progress bar of archive page keep in loading

Service System: Ubuntu 16.04.2 LTS

**Comment by pfrazee** [comment]
Hi @Evanlai8, can you clarify for me:

> In Service, metadata was uploaded succeesfully but the content was failed, the progress bar of archive page keep in loading

Two questions:

 1. What percentage did the progress bar stop at?
 2. How do you know the metadata succeeded but the content failed?

**Comment by Evanlai8** [comment]
thanks for you reply, for your question
1. the percentage was stoped at zero, just the icon shows loading.
2. I found data in .hashbase/archives/.. , I can see the metadata folder but no content folder, while in Local computer I can see both.

I have found that the metadata folder was generate by _loadArchiveInner () in archiver file, it's not uploaded from my local computer.

this.swarm.on('connection') function didn't work in my Service , but work in my local computer
I have tried to use dat doctor between Service and my local computer, it shows connection success. 
so I think it could be the connection problem

**Comment by pfrazee** [comment]
@Evanlai8 Ok solid detective work.

That definitely sounds like a connection problem. Does your server have a firewall on? If so, try opening port 3282. If not, let me know.

**Comment by Evanlai8** [comment]
Yeah, the reason was I didn't open the swarm port. though it is not port 3282. Everytime I restart  the server,  the port is different.  
I can uploaded content now. thanks @pfrazee , but the process is not so fluency, sometime is failed

I have two question
1. If my net can't connect to discovery1.publicbits.org/discovery2.publicbits.org , does it means I cant open the dat sites ?
2. Is it possible that everyone can build a site like publicbits.org to sync the data, so that everyone can connect to dat site even though publicbits.org is closed.

**Comment by pfrazee** [comment]
Hmm, not on port 3282 sounds like an issue. I'll look into that

> 1. If my net can't connect to discovery1.publicbits.org/discovery2.publicbits.org , does it means I cant open the dat sites ?

Correct, they're a part of the discovery network, similar to trackers in bittorrent.

> 2. Is it possible that everyone can build a site like publicbits.org to sync the data, so that everyone can connect to dat site even though publicbits.org is closed.

We're in the process of replacing those servers with a DHT. It should happen by summer.

**Comment by Evanlai8** [comment]
Thanks for your reply. This issue could be close now
> Just found that the port could be set in "this.swarm.listen"
> the default port is set as 0, that's why the port is  different when restart server
