### ISSUE TITLE
PasteDat, along with some other websites, give a 404 error

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/hashbase#98]
Some websites, like [PasteDat](https://hashbase.io/taravancil/pastedat) and [rss-reader](https://hashbase.io/pfrazee/rss-reader), give a 404 error.

[You've probably already become aware of the issue](https://twitter.com/pfrazee/status/1008806575170031621), but thought of posting for the very unlikely case that you thought it was related to webdesserts only.

Thanks as always! :-)

**Comment by taravancil** [comment]
Thanks this is due to a URL policy change we made yesterday.

**Comment by taravancil** [comment]
@pfrazee we'll need to update the links on the homepage and deploy it today if possible

**Comment by pfrazee** [comment]
I'm on it!

**Comment by pfrazee** [comment]
Fixed. Thanks for reporting!!
